modLoader="javafml" #mandatory
loaderVersion="[31,)" #mandatory This is typically bumped every Minecraft version by Forge. See our download page for lists of versions.
[[mods]] #mandatory
modId="boggers" #mandatory
version="${file.jarVersion}" #mandatory
displayName="Boggers" #mandatory
credits="HoboJoe4427" #optional
authors="Coda1552, Mr. Esuoh" #optional
description='''
Boggers, dude!'''